// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID
	FirstName sql.NullString
	LastName  sql.NullString
	Email     sql.NullString
	Phone     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}
