POST http://localhost:8081/api/v1/users/login
Content-Type: application/json

{
  "Email": "zain2@email.com",
  "Password": "234"
}

### for registration
POST http://localhost:8081/api/v1/users
Content-Type: application/json

{
  "FirstName": "Zain",
  "LastName": "Siddiqui",
  "Email": "zain2@email.com",
  "phone": "030301210",
  "Password": "234"
}

###
### GET request to check api status
GET http://localhost:8081/api/v1/health

###